name: siam_internal_app
description: Internal Employee Leave Request App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  riverpod: 2.5.1
  go_router: ^17.0.0
  dio: ^5.4.0
  flutter_dotenv: ^6.0.0
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^10.0.0
  intl: ^0.20.2
  image_picker: ^1.2.1
  file_picker: ^10.3.8
  flutter_easyloading: ^3.0.5
  fluttertoast: ^9.0.0
  json_annotation: ^4.9.0
  state_notifier: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - .env
